### ISSUE TITLE
Bump URI dependency to 0.8

### ISSUE THREAD

**Issue by collinhundley** [Zewo/SQL#12]
SPM dependencies are a pain right now. Bumping the URI minor version to 8 would resolve some conflicts I'm encountering, and might for other people as well.

**Comment by paulofaria** [comment]
@collinhundley yeah man! the infinite snapshots are driving me crazy! what exactly are the issues you're having?

**Comment by collinhundley** [comment]
The conflict actually occurs in [open-swift/C7](https://github.com/open-swift/C7), but the branch diverges here in this package. URI v0.7 requires C7 v0.7, but other packages in my project require C7v0.8.  Bumping URI to v0.8 here will also bump the C7 dependency to v0.8.

I'm actually pretty new to SPM - are there better ways to deal with dependency conflicts?

**Comment by paulofaria** [comment]
@collinhundley unfortunately not yet. SPM itself is very new. :/ ok let me update.

**Comment by collinhundley** [comment]
Thanks!

**Comment by Danappelxx** [comment]
Bumped dependencies and tagged as 0.8.0 👍
